HandyRides/HandyRides/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rides/', include('rides.urls')),
    path('add_ride/',include('add_ride.urls')),
    path('', TemplateView.as_view(template_name="index.html"))
]

HandyRides/add_ride/urls.py
from django.urls import path

from . import views

app_name = 'add_ride'
urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create')

]

HandyRides/rides/urls.py
from django.urls import path

from . import views

app_name = 'rides'
urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create')

]

HandyRides/add_ride/models.py
from django.db import models
from django.core.validators import RegexValidator
import re
# Create your models here.

# https://stackoverflow.com/questions/59480134/how-to-store-a-phone-number-in-django-model
# error message when a wrong format entered
phone_message = 'Phone number must be entered in the format: 999999999+' 

 # your desired format 
phone_regex = RegexValidator(
    # regex=r^[-+]?[0-9]+$,
    regex = r'^[0-9]+$',
    message=phone_message
)



class Person(models.Model):
  first_name = models.CharField(max_length=64)
  last_name = models.CharField(max_length=64)
  email = models.CharField(max_length=64)
  rating = models.IntegerField()
  # phone_number = models.IntegerField()
  # finally, your phone number field
  phone_number = models.CharField(validators=[phone_regex], max_length=60)
  # phone_number = models.CharField(max_length=60)
  origination_address = models.CharField(max_length=64)
  origination_city = models.CharField(max_length=64)
  origination_state = models.CharField(max_length=2)
  destination_address = models.CharField(max_length=64)
  destination_city = models.CharField(max_length=64)
  destination_state = models.CharField(max_length=2)
  date = models.DateField()
  time = models.TimeField()
  taking_passengers = models.BooleanField(default=False)
  seats_available = models.IntegerField(default=0)
  vehicle_model = models.CharField(max_length=64)

HandyRides/rides/models.py
from django.db import models
from django.core.validators import RegexValidator
import re
# Create your models here.

# https://stackoverflow.com/questions/59480134/how-to-store-a-phone-number-in-django-model
# error message when a wrong format entered
phone_message = 'Phone number must be entered in the format: 05999999999' 

 # your desired format 
phone_regex = RegexValidator(
    # regex=r^[-+]?[0-9]+$,
    regex = r'^[0-9]+$',
    message=phone_message
)



class Person(models.Model):
  first_name = models.CharField(max_length=64)
  last_name = models.CharField(max_length=64)
  email = models.CharField(max_length=64)
  rating = models.IntegerField()
  # phone_number = models.IntegerField()
  # finally, your phone number field
  phone_number = models.CharField(validators=[phone_regex], max_length=60)
  # phone_number = models.CharField(max_length=60)
  origination_address = models.CharField(max_length=64)
  origination_city = models.CharField(max_length=64)
  origination_state = models.CharField(max_length=2)
  destination_address = models.CharField(max_length=64)
  destination_city = models.CharField(max_length=64)
  destination_state = models.CharField(max_length=2)
  date = models.DateField()
  time = models.TimeField()
  taking_passengers = models.BooleanField(default=False)
  seats_available = models.IntegerField(default=0)
  vehicle_model = models.CharField(max_length=64)

HandyRides/add_ride/forms.py
from django import forms
from rides.models import Person


class RideForm(forms.Form):
  search_city = forms.CharField(label='search_city', max_length=64, required=False)
  search_state = forms.CharField(label='search_state', max_length=64, required=False)

# https://docs.djangoproject.com/en/3.0/topics/db/models/#meta-options
# Model metadata is “anything that’s not a field”,
class NewRideForm(forms.ModelForm):
  class Meta:
    model = Person
    # fields = ['first_name','phone_number']
    exclude = []

HandyRides/rides/forms.py
from django import forms
from .models import Person


class RideForm(forms.Form):
  search = forms.CharField(label='Search term', max_length=64, required=False)


class NewRideForm(forms.ModelForm):
  class Meta:
    model = Person
    exclude = []

HandyRides/add_ride/views.py
from django.shortcuts import render, redirect
import logging
from .models import Person

# relative import of forms
from .forms import RideForm, NewRideForm
# Create your views here.
logger = logging.getLogger(__name__)

def index(request):
# make a dict named context
  context = {}
# check requests and filter.
  if "search_state" in request.GET:
    search = request.GET["search_state"]
    context["people"] = Person.objects.filter(
        origination_state__icontains=search) | Person.objects.filter(destination_state__icontains=search)
  if "search_city" in request.GET:
    search = request.GET["search_city"]
    context["people"] = context["people"].filter(
        origination_city__icontains=search) | Person.objects.filter(destination_city__icontains=search)
  
  context["form"] = RideForm()
  context["new_ride_form"] = NewRideForm()
  # context has items "people", "form", "new_ride_form"
  # people = the search results
  # form is 
  # new_ride_form =

  # https://docs.djangoproject.com/en/3.1/topics/http/shortcuts/
  # render function is a django shortcut.
  # takes arguments request, templatename, and context
  # returns a httpresponse object with the rendered text.

  # request is The request object used to generate this response.
  # template is the full name of a template to use or sequence of template names
  # context is A dictionary of values to add to the template context.
  return render(request, "add_ride_view.html", context)

def create(request):
  if request.method == "POST":
    new_ride = NewRideForm(request.POST)
    if new_ride.is_valid():
      new_ride.save()
    else:
      new_ride.save()
  # Returns an HttpResponseRedirect to the appropriate URL for the arguments passed.
  return redirect("/rides")

HandyRides/rides/views.py
from django.shortcuts import render, redirect

from .models import Person

# relative import of forms
from .forms import RideForm, NewRideForm
# Create your views here.


def index(request):
# make a dict named context
  context = {}
# check requests and filter.
  if "search_state" in request.GET:
    search = request.GET["search_state"]

    context["people"] = Person.objects.filter(
        origination_state__icontains=search) | Person.objects.filter(destination_state__icontains=search) | Person.objects.filter(destination_city__icontains=search)
  
  if "search_city" in request.GET:
    search = request.GET["search_city"]

    context["people"] = context["people"].filter(
        origination_city__icontains=search) | Person.objects.filter(destination_state__icontains=search) | Person.objects.filter(destination_city__icontains=search)
  	
  context["form"] = RideForm()
  context["new_ride_form"] = NewRideForm()
  # context has items "people", "form", "new_ride_form"
  # people = the search results
  # form is 
  # new_ride_form =

  # https://docs.djangoproject.com/en/3.1/topics/http/shortcuts/
  # render function is a django shortcut.
  # takes arguments request, templatename, and context
  # returns a httpresponse object with the rendered text.

  # request is The request object used to generate this response.
  # template is the full name of a template to use or sequence of template names
  # context is A dictionary of values to add to the template context.
  return render(request, "index_view.html", context)

def create(request):
  # if request.method == "POST":
  #   new_ride = NewRideForm(request.POST)
  #   new_ride.save()
  # Returns an HttpResponseRedirect to the appropriate URL for the arguments passed.
  return redirect("/rides")

HandyRides/add_ride/templates/add_ride_view.html
{% extends "add_ride.html" %}

{% block content %}
<!-- figure this out -->
<style type="text/css">
    input[type=text], select {
      width: 100%;
      padding: 12px 20px;
      margin: 8px 0;
      display: inline-block;
      border: 1px solid #ccc;
      border-radius: 4px;
      box-sizing: border-box;
    }
    input[type=text]:focus{
      background-color: lightblue;
    }
    input[type=submit] {
      width: 100%;
      padding: 14px 20px;
      margin: 8px 0;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }
    input[type=submit]:hover {
      background-color: rgba(100,100,100,1);
    }
  </style>
<div class="main"> 
  <table>
      {% for person in people %}
      <tr>
          <td>{{ person.first_name }}</td> 
          <td>{{ person.origination }}</td>
          <td>{{ person.destination_city }}</td> 
          <td>{{ person.destination_state }}</td> 
          <td>{{ person.date }}</td> 
          <td>{{ person.time }}</td> 
          <td>{{ person.taking_passengers }}</td>
          <td>{{ person.seats_available }}</td> 
      </tr>
      {% endfor %} 
  </table>
</div> 
<div>
  <form action="{% url 'add_ride:create' %}" method="POST" style="font-size: 36px">
      <!-- protects from csrf attack -->
      {% csrf_token %}
      <!--  double_curly_braces reserve space for your data -->
      <!-- new_ride_form is declared in views.py -->
      <!-- context["form"] = RideForm()
           context["new_ride_form"] = NewRideForm() -->
      {{ new_ride_form }}
      <input type="submit" value="Submit" style="font-size: 24px">
      <h2 style="font-size:25px;padding-top: 40px"><a href="/rides">Search for a Ride</h2>
  </form>
</div>
{% endblock %}

HandyRides/rides/templates/index_view.html
{% extends "base.html" %}
{% block content %}
<!-- figure this out -->
<div class="main"> 
  <style type="text/css">
    td {
      border: 1px solid black;
    }
    th{
      border: 4px solid black;
    } 
    table{
      border-collapse: collapse;
      text-align: center;
      font-size: 24px;
      background-color: rgba(235,235,255,1)
    }
    tr:hover {
      background-color: #ffa;
    }

  </style>
  <table>
    <tr>
      <th>FirstName</th>
      <th>LastName</th>
      <th>Email</th>
      <th>Phone_Number</th>
      <th>Rating</th>
      <th>O_Addr</th>
      <th>O_City</th>
      <th>O_State</th>
      <th>D_Addr</th>
      <th>D_City</th>
      <th>D_State</th>
      <th>Date</th>
      <th>Time</th>
      <th>Taking_Passenger</th>
      <th>Seats_Available</th>
      <th>Vehicle_Model</th>
    </tr>
    {% for person in people %}
    <tr>
        <td>{{ person.first_name }}</td> 
        <td>{{ person.last_name }}</td> 
        <td>{{ person.email }}</td> 
        <td>{{ person.phone_number }}</td>
        <td>{{ person.rating}}</td> 
        <td>{{ person.origination_address}}</td>
        <td>{{ person.origination_city }}</td>
        <td>{{ person.origination_state }}</td>
        <td>{{ person.destination_address}}</td>
        <td>{{ person.destination_city }}</td> 
        <td>{{ person.destination_state }}</td> 
        <td>{{ person.date }}</td> 
        <td>{{ person.time }}</td> 
        <td>{{ person.taking_passengers }}</td>
        <td>{{ person.seats_available }}</td> 
        <td>{{ person.vehicle_model }}</td> 
    </tr>
    {% endfor %} 
  </table>
</div> 

<form action="{% url 'rides:index' %}" method="get" style="padding-top: 40px;font-size: 36px">
    {{ form }}
    <input type="submit" value="Submit" onclick="return checkForm(this.parentNode);" style="font-size: 24px">
</form>
<!-- <form action="{% url 'rides:create' %}" method="post"> -->
    <!-- protects from csrf attack -->
    <!-- {% csrf_token %} -->
    <!--  double_curly_braces reserve space for your data -->
    <!-- new_ride_form is declared in views.py -->
    <!-- context["form"] = RideForm()
         context["new_ride_form"] = NewRideForm() -->
    <!-- {{ new_ride_form }} -->
    <!-- <input type="submit" value="Submit"> -->
<!-- </form> -->
<h2 style="font-size:25px;"><a href="/add_ride">Add a Ride</h2>

{% endblock %}

HandyRides/templates/add_ride.html
{% load static %}

<html>
  <head>
    <div class="logo_small">
      <img src="{% static 'logo.png' %}" alt="Image of logo" class="logo_small_image">
    </div>
  <script src="{% static 'main.js' %}"></script>
  <link rel="stylesheet" href="{% static 'main.css' %}"/>
</head>

<title> ORF 401: Spring 2020 </title>
  <body bgcolor="white" text="black" onload="checkCookie('ORF401', 1, 4)">
    <center>
      <h1 style="font-size:60px;">Add rides Here</h1>

      <img src="{% static 'logo.png' %}" alt="Image of logo" width="750px" height="350px" style = "padding-bottom: 100px;">

      {% block content %}
      {% endblock %}
      <h2 style="font-size:25px;"><a href="/">Return to splash page</h2>
    </center>
  </body>
</html>

HandyRides/templates/base.html
{% load static %}

<html>
  <head>
    <div class="logo_small">
      <img src="{% static 'logo.png' %}" alt="Image of logo" class="logo_small_image">
    </div>
  <script src="{% static 'main.js' %}"></script>
  <link rel="stylesheet" href="{% static 'main.css' %}"/>
</head>

<title> ORF 401: Spring 2020 </title>
  <body bgcolor="white" text="black" onload="checkCookie('ORF401', 1, 4)">
    <center>
      <h1 style="font-size:60px;">Welcome to</h1>

      <img src="{% static 'logo.png' %}" alt="Image of logo" width="750px" height="350px" style = "padding-bottom: 100px;">

      {% block content %}
      {% endblock %}
      <h2 style="font-size:25px;"><a href="/">Return to splash page</h2>
    </center>
  </body>
</html>

HandyRides/templates/index.html
{% load static %}

<html>
  <head>
    <div class="logo_small">
      <img src="{% static 'logo.png' %}" alt="Image of logo" class="logo_small_image">
    </div>
	  <script src="{% static 'main.js' %}"></script>
	  <link rel="stylesheet" href="{% static 'main.css' %}"/>
	</head>

	<title> ORF 401: Spring 2020 </title>

  <body bgcolor="white" text="black">
    <div id="banner">
    </div>
    <center>
      <h1 >ridedirs splash page</h1>
      <body>

    <div class="container">
      <img src="{% static 'logo_old.jpg' %}" alt="Image of car" class="image">
      <div class="overlay">
        <div class="text"><a href="/rides/">Find your rides!!</div>
      </div>
    </div>

      <h2 > "Take a ride with us" </h2>
      
      {% block content %}
      {% endblock %}

      <!-- <h1 style="font-size:40px;"> <a href="http://127.0.0.1:8000/rides/">Find your rides!!</h1> -->
    </center>
  </body>

</head> 

</html>